general.import = [
  # "~/.config/alacritty/nord.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 12.0

[font.bold]
family = "SauceCodePro Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "SauceCodePro Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "SauceCodePro Nerd Font Mono"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font Mono"
style = "Regular"
